version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    restart: unless-stopped

  hugging-cat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hugging-cat-app
    ports:
      - "7000:7000"
    depends_on:
      - qdrant
    environment:
      QDRANT_URL: http://qdrant:6333
    restart: unless-stopped
